services:
  postgres:
    image: postgres
    env_file: ./docker/postgres/.env
    ports:
      - 4243:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
    volumes:
      - pg-data:/var/lib/postgresql
    restart: unless-stopped

  redis:
    build:
      context: docker/redis
    env_file: ./docker/redis/.env
    ports:
      - 12312:6379
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  bot:
    image: ghcr.io/astral-sh/uv:python3.14-trixie
    env_file:
      - ./docker/bot/.env
      - ./docker/postgres/.env
      - ./docker/redis/.env
      - ./docker/yandex/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - bot-env:/app/.venv
    working_dir: /app
    command: ["uv", "run", "bot"]
    restart: unless-stopped

volumes:
  pg-data:
  bot-env:
