name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run unit tests using uv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: ./.github/actions/install-project

      - name: Run unit tests
        run: uv run pytest tests/units -q

  functional-tests:
    name: Run functional tests using uv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: ./.github/actions/install-project

      - name: Run functional tests
        run: uv run pytest tests/functional -q || if [[ $? -ne 5 ]]; then exit $?; fi
