name: CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ruff:
    name: Run ruff check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v4.0.0
        with:
          version-file: pyproject.toml
      - run: ruff check

  mypy:
    name: Run mypy check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-project
      - run: uv run mypy .

  unit-tests:
    name: Run unit tests using uv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: ./.github/actions/install-project

      - name: Run unit tests
        run: uv run pytest tests/units -q

  functional-tests:
    name: Run functional tests using uv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: ./.github/actions/install-project

      - name: Run functional tests
        run: uv run pytest tests/functional -q || if [[ $? -ne 5 ]]; then exit $?; fi
